// SPDX-License-Identifier: MIT
// Copyright (c) 2025 Copilot-for-Consensus contributors

import { useEffect, useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { fetchReport, Report } from '../api'
import ReactMarkdown from 'react-markdown'

export function ReportDetail() {
  const { reportId } = useParams()
  const [report, setReport] = useState<Report | null>(null)
  const [error, setError] = useState<string | null>(null)
  const [loading, setLoading] = useState(false)

  useEffect(() => {
    if (!reportId) return
    let cancelled = false
    setLoading(true)
    setError(null)
    fetchReport(reportId)
      .then(r => { if (!cancelled) setReport(r) })
      .catch(e => { if (!cancelled) setError(e?.message || 'Failed to load report') })
      .finally(() => { if (!cancelled) setLoading(false) })
    return () => { cancelled = true }
  }, [reportId])

  function copy(text: string) {
    navigator.clipboard.writeText(text)
  }

  if (loading) return <div className="no-reports">Loading…</div>
  if (error === 'NOT_FOUND') return <div className="no-reports">Report not found</div>
  if (error) return <div className="no-reports">{error}</div>
  if (!report) return null

  return (
    <div>
      <Link to="/reports" className="back-link">← Back to Reports</Link>
      <h1>Report Details</h1>

      <div className="header-info">
        <div className="info-grid">
          <div className="info-item">
            <div className="info-label">Report ID</div>
            <div className="info-value">
              {report._id}
              <button className="copy-btn" onClick={() => copy(report._id)}>Copy</button>
            </div>
          </div>
          <div className="info-item">
            <div className="info-label">Thread ID</div>
            <div className="info-value">
              {report.thread_id}
              <button className="copy-btn" onClick={() => copy(report.thread_id)}>Copy</button>
            </div>
          </div>
          <div className="info-item">
            <div className="info-label">Generated At</div>
            <div className="info-value">{report.generated_at}</div>
          </div>
          <div className="info-item">
            <div className="info-label">Generated By</div>
            <div className="info-value">{report.generated_by}</div>
          </div>
        </div>
        
        {/* Add navigation to thread view */}
        <div style={{ marginTop: '15px' }}>
          <Link 
            className="view-thread-btn" 
            to={`/threads/${report.thread_id}/messages`}
          >
            💬 View Underlying Discussion
          </Link>
        </div>
      </div>

      <div className="metadata-section">
        <h2>Performance Metrics</h2>
        <div className="info-grid">
          <div className="info-item">
            <div className="info-label">LLM Model</div>
            <div className="info-value">{report.metadata?.llm_model ?? 'N/A'}</div>
          </div>
          <div className="info-item">
            <div className="info-label">Prompt Tokens</div>
            <div className="info-value">{report.metadata?.tokens_prompt ?? 0}</div>
          </div>
          <div className="info-item">
            <div className="info-label">Completion Tokens</div>
            <div className="info-value">{report.metadata?.tokens_completion ?? 0}</div>
          </div>
          <div className="info-item">
            <div className="info-label">Latency</div>
            <div className="info-value">{report.metadata?.latency_ms ?? 0} ms</div>
          </div>
        </div>
      </div>

      <div className="summary-section">
        <h2>Summary</h2>
        <div className="markdown">
          <ReactMarkdown>{report.content_markdown || ''}</ReactMarkdown>
        </div>
      </div>

      <div className="citations-section">
        <h2>Citations ({report.citations?.length ?? 0})</h2>
        {report.citations && report.citations.length > 0 ? (
          <div className="citations-list">
            {report.citations.map((c, idx) => (
              <div className="citation-card" key={`${c.message_id}-${idx}`}>
                <div className="citation-header">
                  <span className="citation-number">#{idx + 1}</span>
                  <span className="citation-id-badge">{(c.message_id ?? '').slice(0,16)}...</span>
                </div>
                {c.quote ? (
                  <div className="citation-text">“{c.quote}”</div>
                ) : (
                  <div className="citation-text no-quote"><em>No text snippet available</em></div>
                )}
                <div className="citation-metadata">
                  <div className="metadata-row">
                    <span className="metadata-label">Message ID:</span>
                    <span className="metadata-value citation-id">{c.message_id || 'unknown'}</span>
                    <button className="copy-btn-small" onClick={() => copy(c.message_id || 'unknown')} title="Copy message ID">Copy</button>
                  </div>
                  <div className="metadata-row">
                    <span className="metadata-label">Chunk ID:</span>
                    <span className="metadata-value citation-id">{c.chunk_id || 'unknown'}</span>
                    <button className="copy-btn-small" onClick={() => copy(c.chunk_id || 'unknown')} title="Copy chunk ID">Copy</button>
                  </div>
                  {/* Add clickable link to view in thread context */}
                  <div className="citation-actions">
                    <Link 
                      className="citation-link" 
                      to={`/threads/${report.thread_id}/messages?highlight=${c.message_id}`}
                    >
                      📍 View in Thread
                    </Link>
                  </div>
                </div>
              </div>
            ))}
          </div>
        ) : (
          <p style={{ color: '#666' }}>No citations available.</p>
        )}
      </div>
    </div>
  )
}
