# SPDX-License-Identifier: MIT
# Copyright (c) 2025 Copilot-for-Consensus contributors

"""Example atheris fuzzing test.

Atheris is a coverage-guided Python fuzzing engine. It uses libFuzzer to 
generate inputs that maximize code coverage and find bugs.

IMPORTANT: Atheris tests run as standalone scripts (python test_atheris_example.py),
NOT through pytest. This is because atheris uses libFuzzer's own execution model
which is incompatible with pytest's test runner. The CI workflow runs this file
directly with a shell timeout rather than using pytest --timeout.

Usage:
    python tests/test_atheris_example.py -atheris_runs=1000
"""

import sys

try:
    import atheris
except ImportError:
    # Atheris may not be available on all platforms (requires compilation)
    atheris = None


def fuzz_json_parser(data: bytes) -> None:
    """Example fuzzing target: test JSON parsing robustness.
    
    This demonstrates fuzzing a parser to find:
    - Crashes from malformed input
    - Excessive memory usage
    - Infinite loops
    - Unexpected exceptions
    
    Args:
        data: Random bytes generated by the fuzzer
    """
    import json
    
    try:
        # Convert bytes to string
        if not data:
            return
            
        input_str = data.decode("utf-8", errors="ignore")
        
        # Try to parse as JSON - should handle any input gracefully
        json.loads(input_str)
        
    except (json.JSONDecodeError, UnicodeDecodeError, ValueError):
        # These are expected exceptions for malformed input
        pass
    except Exception as e:
        # Unexpected exceptions might indicate a bug
        # In production code, you'd want to investigate these
        print(f"Unexpected exception: {type(e).__name__}: {e}")
        raise


def main() -> None:
    """Set up and run the fuzzer."""
    if atheris is None:
        print("Atheris not available - skipping fuzzing test")
        print("Install with: pip install atheris")
        return
    
    atheris.Setup(sys.argv, fuzz_json_parser)
    atheris.Fuzz()


if __name__ == "__main__":
    main()
